In [3]:
import pandas as pd

# Load the combined cleaned data
file_path = 'combinedCleanedData.csv'
df = pd.read_csv(file_path)

# Function to check for missing values
def check_missing_values(df, name):
    missing = df.isnull().sum()
    missing = missing[missing > 0]
    if not missing.empty:
        print(f"Remaining missing values in {name} Data:")
        print(missing)
    else:
        print(f"No missing values in {name} Data.")

# Function to check data types
def check_data_types(df):
    print("Data types:")
    print(df.dtypes)
    print("\n")

# Function to check for duplicates
def check_duplicates(df):
    duplicates = df.duplicated().sum()
    print(f"Number of duplicate rows: {duplicates}")
    return duplicates

# Function to check value ranges and validity
def check_value_ranges(df):
    print("Summary statistics:")
    print(df.describe())
    print("\n")

# Function to check unique values in categorical columns
def check_unique_values(df, columns):
    for col in columns:
        print(f"Unique values in {col}:")
        print(df[col].unique())
        print("\n")

# Check for missing values
check_missing_values(df, "Combined")

# Check data types
check_data_types(df)

# Check for duplicates
num_duplicates = check_duplicates(df)
if num_duplicates > 0:
    df = df.drop_duplicates()

# Check value ranges and validity
check_value_ranges(df)

# Check unique values in categorical columns
categorical_columns = ['Name', 'Nationality', 'Club', 'Preferred Foot', 'Work Rate']
check_unique_values(df, categorical_columns)

# Additional cleaning for 'Value' and 'Wage' columns
if 'Value' in df.columns:
    df['Value'] = df['Value'].replace({'\€': '', 'M': 'e+6', 'K': 'e+3'}, regex=True).astype(float)
if 'Wage' in df.columns:
    df['Wage'] = df['Wage'].replace({'\€': '', 'M': 'e+6', 'K': 'e+3'}, regex=True).astype(float)

# Verify the changes
check_value_ranges(df)

# Save the cleaned data to a new CSV file if needed
cleaned_file_path = 'cleaned_combined_data.csv'
df.to_csv(cleaned_file_path, index=False)

print("Data cleaning complete. Cleaned data saved to", cleaned_file_path)

# Print the total number of rows and columns in the cleaned dataset
total_rows = df.shape[0]
total_columns = df.shape[1]
print("Total rows in the cleaned dataset:", total_rows)
print("Total columns in the cleaned dataset:", total_columns)

No missing values in Combined Data.
Data types:
Body Type                    object
Best Overall Rating         float64
Skill Moves                 float64
Joined                       object
Height                       object
Weight                       object
Release Clause               object
Loaned From                  object
Name                         object
Special                       int64
Age                           int64
Wage                         object
ID                            int64
International Reputation    float64
Club                         object
Club Logo                    object
Preferred Foot               object
Real Face                    object
Weak Foot                   float64
Overall                       int64
Potential                     int64
Nationality                  object
Flag                         object
Photo                        object
Value                        object
Work Rate                    object
Contract Valid Until         object
Position                     object
dtype: object


Number of duplicate rows: 0
Summary statistics:
       Best Overall Rating   Skill Moves       Special           Age  \
count         51478.000000  51478.000000  51478.000000  51478.000000
mean             45.802867      2.404542   1604.291018     24.611679
std              31.381607      0.779076    273.891143      4.991497
min               3.000000      1.000000    571.000000     15.000000
25%               3.000000      2.000000   1455.000000     21.000000
50%              64.000000      2.000000   1631.000000     24.000000
75%              70.000000      3.000000   1795.000000     28.000000
max              93.000000      5.000000   2341.000000     54.000000

                  ID  International Reputation     Weak Foot       Overall  \
count   51478.000000              51478.000000  51478.000000  51478.000000
mean   229683.391896                  1.140662      2.962469     65.891293
std     37379.090526                  0.450569      0.674759      7.450315
min         2.000000                  1.000000      1.000000     28.000000
25%    212261.000000                  1.000000      3.000000     61.000000
50%    239256.000000                  1.000000      3.000000     66.000000
75%    255889.750000                  1.000000      3.000000     71.000000
max    271340.000000                  5.000000      5.000000     93.000000

          Potential
count  51478.000000
mean      72.020222
std        6.052750
min       38.000000
25%       68.000000
50%       72.000000
75%       76.000000
max       95.000000


Unique values in Name:
[' L. Suárez' ' K. De Bruyne' ' Bruno Fernandes' ... 'A. Demir'
 '21\xa0S. Czajor' '21\xa0F. Jakobsson']


Unique values in Nationality:
['Uruguay' 'Belgium' 'Portugal' 'France' 'Argentina' 'Brazil' 'Germany'
 'Netherlands' 'Spain' 'Croatia' 'Austria' 'Chile' 'Serbia' 'Italy'
 'England' 'Wales' 'Egypt' 'Senegal' 'Denmark' 'Poland' 'Ghana' 'Mexico'
 'Bosnia Herzegovina' 'Colombia' 'Ecuador' 'Turkey' 'Peru' 'Slovakia'
 'Ukraine' 'Central African Republic' 'Ivory Coast' 'Russia'
 'Korea Republic' 'Switzerland' 'Scotland' 'North Macedonia' 'Morocco'
 'Nigeria' 'Czech Republic' 'Canada' 'Algeria' 'Norway' 'China PR'
 'Paraguay' 'Angola' 'Montenegro' 'Finland' 'Guinea' 'Armenia' 'Benin'
 'Gabon' 'Iraq' 'Liberia' 'Israel' 'Iceland' 'Australia'
 'Republic of Ireland' 'Slovenia' 'United States' 'Northern Ireland'
 'Romania' 'Cameroon' 'Greece' 'Sweden' 'Kosovo' 'Tunisia' 'Moldova'
 'Venezuela' 'Bulgaria' 'Honduras' 'Mali' 'Guinea Bissau' 'Uzbekistan'
 'DR Congo' 'New Zealand' 'Saudi Arabia' 'Dominican Republic'
 'Burkina Faso' 'Bolivia' 'Zambia' 'Fiji' 'Curacao' 'Japan' 'Jamaica'
 'Costa Rica' 'Hungary' 'Cuba' 'Cyprus' 'South Africa' 'Cape Verde'
 'Albania' 'Kenya' 'Zimbabwe' 'Syria' 'Equatorial Guinea' 'Congo'
 'Georgia' 'Comoros' 'Iran' 'Haiti' 'Gambia' 'Madagascar' 'Panama'
 'Chinese Taipei' 'Kazakhstan' 'Togo' 'Trinidad & Tobago' 'Thailand'
 'Saint Kitts and Nevis' 'Eritrea' 'Tanzania' 'United Arab Emirates'
 'Libya' 'Bermuda' 'Mozambique' 'Rwanda' 'Faroe Islands' 'Chad'
 'Luxembourg' 'Grenada' 'Sierra Leone' 'Palestine' 'São Tomé & Príncipe'
 'Antigua & Barbuda' 'Guyana' 'Guam' 'Puerto Rico' 'Latvia' 'Belize'
 'El Salvador' 'Liechtenstein' 'Suriname' 'Azerbaijan' 'Montserrat'
 'Lithuania' 'Burundi' 'Uganda' 'Belarus' 'Namibia' 'Afghanistan'
 'Philippines' 'Korea DPR' 'Lebanon' 'Mauritania' 'Bahrain' 'Estonia'
 'India' 'Aruba' 'Qatar' 'Jordan' 'New Caledonia' 'Niger' 'Vietnam'
 'Sudan' 'Gibraltar' 'Sri Lanka' 'Saint Lucia' 'Malawi' 'Malta'
 'Hong Kong' 'Andorra' 'Nicaragua' 'South Sudan' 'Papua New Guinea'
 'Malaysia' 'Indonesia' 'Brunei Darussalam' 'Macau' 'Oman' "Côte d'Ivoire"
 'Bosnia and Herzegovina' 'Congo DR' 'Cape Verde Islands'
 'Trinidad and Tobago' 'São Tomé e Príncipe' 'Antigua and Barbuda'
 'Kyrgyzstan' 'Barbados' 'Bhutan' 'Mauritius' 'Guatemala' 'Kuwait' 'Laos'
 'Singapore' 'Ethiopia' 'San Marino']


Unique values in Club:
['Atlético Madrid' 'Manchester City' 'Manchester United' ...
 'Excelsior Mouscron' 'Partick Thistle FC' 'FC Hradec Králové']


Unique values in Preferred Foot:
['Right' 'Left']


Unique values in Work Rate:
['High/ Medium' 'High/ High' 'Medium/ Medium' 'Medium/ High' 'Medium/ Low'
 'High/ Low' 'Low/ High' 'N/A/ N/A' 'Low/ Medium' 'Low/ Low']


Summary statistics:
       Best Overall Rating   Skill Moves       Special           Age  \
count         51478.000000  51478.000000  51478.000000  51478.000000
mean             45.802867      2.404542   1604.291018     24.611679
std              31.381607      0.779076    273.891143      4.991497
min               3.000000      1.000000    571.000000     15.000000
25%               3.000000      2.000000   1455.000000     21.000000
50%              64.000000      2.000000   1631.000000     24.000000
75%              70.000000      3.000000   1795.000000     28.000000
max              93.000000      5.000000   2341.000000     54.000000

                Wage             ID  International Reputation     Weak Foot  \
count   51478.000000   51478.000000              51478.000000  51478.000000
mean     9966.111737  229683.391896                  1.140662      2.962469
std     21004.575157   37379.090526                  0.450569      0.674759
min         0.000000       2.000000                  1.000000      1.000000
25%      1000.000000  212261.000000                  1.000000      3.000000
50%      3000.000000  239256.000000                  1.000000      3.000000
75%      9000.000000  255889.750000                  1.000000      3.000000
max    560000.000000  271340.000000                  5.000000      5.000000

            Overall     Potential         Value
count  51478.000000  51478.000000  5.147800e+04
mean      65.891293     72.020222  2.879260e+06
std        7.450315      6.052750  7.226971e+06
min       28.000000     38.000000  0.000000e+00
25%       61.000000     68.000000  4.000000e+05
50%       66.000000     72.000000  9.000000e+05
75%       71.000000     76.000000  2.200000e+06
max       93.000000     95.000000  1.940000e+08


Data cleaning complete. Cleaned data saved to cleaned_combined_data.csv
Total rows in the cleaned dataset: 51478
Total columns in the cleaned dataset: 28